/* eslint-disable import/order */
import React from 'react';
import Providers from '../components/Providers'; // Import the Providers component
import Headers from '../components/Headers'; // Assuming the Header component exists
import '../styles/globals.css';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Include any necessary head content */}
      </head>
      <body className={inter.className}>
        <Providers>
          <Headers />
          {children}
        </Providers>
      </body>
    </html>
  );
}
